path: ./data # dataset root dir
train:  C:/Users/sarfa/Documents/PythonProject/yolov10-object-detection-custom-data/data/images/train # train images (relative to 'path')
val: C:/Users/sarfa/Documents/PythonProject/yolov10-object-detection-custom-data/data/images/val # val images (relative to 'path')

# Classes
names:
  0: duck
